#!/bin/sh

_DO_AFTER_INTERVAL=1

__do_after_help() {
    echo "Usage: $0 [-h] [-i <interval>] <pid|name> <command> [args...]"
}

while getopts 'hi:' flag; do
    case "$flag" in
        i)
            _DO_AFTER_INTERVAL=$OPTARG
            ;;
        h)
            __do_after_help
            exit 0
    esac

done
shift $(( $OPTIND - 1 ))

if [ -z "$1" ]; then
    __do_after_help 2>&1
    exit 1
fi

_PID="$1"
shift
if [ -z "$( echo $_PID | grep -o '^[0-9]*$' )" ]; then
    # Process name was given
    _PID="$( pgrep $_PID | head -n 1 )"
fi

while true; do
    if [ -z "$( ps aux | awk '{ print $2 }' | grep $_PID )" ]; then
        break
    fi

    sleep $_DO_AFTER_INTERVAL
done

exec "$@"
